In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("C:/Users/sumit/Downloads/titanic.csv")
data.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [3]:
new_data = data[["Pclass","Sex","Age","SibSp","Parch","Fare","Embarked","Survived"]].copy()

In [14]:
new_data.head(3)

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0       3    1  22.0      1      0   7.2500         2         0
1       1    0  38.0      1      0  71.2833         0         1
2       3    0  26.0      0      0   7.9250         2         1

In [9]:
new_data.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

# Handling missing values

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
si = SimpleImputer(strategy="mean")
new_data["Age"] = si.fit_transform(new_data[["Age"]])

In [8]:
new_data["Embarked"] = new_data["Embarked"].fillna(new_data["Embarked"].mode()[0])

# Encoding 

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
new_data["Embarked"] = le.fit_transform(new_data["Embarked"])

In [13]:
le1 = LabelEncoder()
new_data["Sex"] = le.fit_transform(new_data["Sex"])

In [15]:
#Train 3 models and evaluate
    #Logistic Regression
    #Random Forest
    #Support Vector Machine

In [17]:
x = new_data.iloc[:,:-1]
y = new_data["Survived"]

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [72]:
lr = LogisticRegression(max_iter=2000)
lr.fit(x_train,y_train)

LogisticRegression(max_iter=2000)

In [73]:
x_train.shape , y_train.shape

((712, 7), (712,))

In [74]:
lr.score(x_train,y_train)*100 , lr.score(x_test,y_test)*100

(80.19662921348315, 81.00558659217877)

In [50]:
rf = RandomForestClassifier(n_estimators =4)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=4)

In [51]:
rf.score(x_train,y_train)*100 , rf.score(x_test,y_test)*100         #overfitting

(95.36516853932584, 78.2122905027933)

In [30]:
sv = SVC(kernel = "linear")
sv.fit(x_train,y_train)

SVC(kernel='linear')

In [31]:
sv.score(x_train,y_train)*100 , sv.score(x_test,y_test)*100

(78.79213483146067, 78.2122905027933)

# Cross validation 

In [52]:
from sklearn.model_selection import cross_val_score

In [68]:
cross_val_score(LogisticRegression(max_iter = 2000),x,y,cv=5)

array([0.78212291, 0.78089888, 0.78089888, 0.76966292, 0.82022472])

In [70]:
cross_val_score(RandomForestClassifier(),x,y,cv=5)

array([0.78212291, 0.80898876, 0.86516854, 0.78089888, 0.84269663])

In [71]:
cross_val_score(SVC(kernel ="linear"),x,y,cv=5)

array([0.80446927, 0.80898876, 0.78651685, 0.75280899, 0.78651685])

In [ ]:
#Hyperparameter tuning:GridSearchCV ,RandomizedSearchCV

In [75]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [83]:
df = {"C":[0.01, 0.1, 1, 10, 100],"solver":['liblinear'],"penalty":["l2"],"max_iter": [100, 200, 500, 1000] }

In [84]:
gd = GridSearchCV(LogisticRegression(),param_grid = df)
gd.fit(x_train,y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'max_iter': [100, 200, 500, 1000], 'penalty': ['l2'],
                         'solver': ['liblinear']})